spring:
  config:
    import: optional:file:./ai-service/.env[.properties]
    activate:
      on-profile: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        default-requeue-rejected: false


openai:
  api-key: ${OPENAI_API_KEY}
  model: ${OPENAI_MODEL}



server:
  port: ${DEV_PORT:8888}