spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: prod
  rabbitmq:
    host: ${PROD_RABBITMQ_HOST}
    port: ${PROD_RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        default-requeue-rejected: false


openai:
  api-key: ${OPENAI_API_KEY}
  model: ${OPENAI_MODEL}


logging:
  level:
    root: info

server:
  port: ${AI_PROD_PORT:8888}