name: Check PR

on:
  pull_request

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          token: ${{ secrets.PA_TOKEN }}
          java-version: 21
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build All Modules
        run: ./gradlew :api-service:build :ai-service:build :common:build -x test

      - name: Run Tests for All Modules
        run: ./gradlew test
